# Generated by Django 5.2.6 on 2025-10-03 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='author_photo/')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('tg', models.CharField(max_length=150, verbose_name='TG')),
                ('vk', models.CharField(max_length=150, verbose_name='VK')),
                ('ig', models.CharField(max_length=150, verbose_name='IG')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Информация об авторе',
                'verbose_name_plural': 'Информация об авторе',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('image', models.ImageField(upload_to='artworks/')),
                ('description', models.TextField(verbose_name='Описание')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='wzertisAPI.artgroup')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wzertisAPI.collection')),
            ],
        ),
    ]
