version: '3.9'

services:
  backend:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./API:/app
    environment:
      - DJANGO_SETTINGS_MODULE=API.settings  # ← Замени на реальное имя модуля settings.py
      - DEBUG=1
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Front:/app          # монтируем код
      - /app/node_modules     # ← КРИТИЧЕСКИ ВАЖНО: скрываем хостовые node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

volumes:
  postgres_data: