# Front/Dockerfile
FROM node:18

WORKDIR /app

# Копируем package.json и устанавливаем зависимости СНУЛЯ внутри контейнера
COPY package*.json ./

# Удаляем кэш и устанавливаем ВСЁ заново (включая optional)
RUN rm -rf node_modules package-lock.json && \
    npm install

# Копируем остальной код
COPY . .

# Запуск dev-сервера
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]